language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  - php --version
before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cli
